import { HugeiconsIcon } from "@hugeicons/react";
import {
  Mail01Icon,
  SmartPhone01Icon,
  Link01Icon,
  GlobeIcon,
  Facebook01Icon,
  InstagramIcon,
  Linkedin01Icon,
  YoutubeIcon,
  RedditIcon,
  PinterestIcon,
  SnapchatIcon,
  ThreadsIcon,
  BlueskyIcon,
  MastodonIcon,
  TumblrIcon,
  WhatsappIcon,
  TelegramIcon,
  DiscordIcon,
  SignalIcon,
  WechatIcon,
  MessengerIcon,
  SkypeIcon,
  GithubIcon,
  GitlabIcon,
  SpotifyIcon,
  SoundcloudIcon,
  LastFmIcon,
  TwitchIcon,
  Kickstarter01Icon,
  ShopifyIcon,
  PaypalIcon,
  StripeIcon,
  WebflowIcon,
  WordpressIcon,
  ZoomIcon,
  WikipediaIcon,
  PexelsIcon,
  UnsplashIcon,
} from "@hugeicons/core-free-icons";

const iconMap: Record<string, unknown> = {
  PHONE_NUMBER: SmartPhone01Icon,
  EMAIL: Mail01Icon,
  SOCIAL_MEDIA_LINK: Link01Icon,
  WEBSITE_LINK: GlobeIcon,
  FACEBOOK: Facebook01Icon,
  INSTAGRAM: InstagramIcon,
  LINKEDIN: Linkedin01Icon,
  YOUTUBE: YoutubeIcon,
  REDDIT: RedditIcon,
  PINTEREST: PinterestIcon,
  SNAPCHAT: SnapchatIcon,
  THREADS: ThreadsIcon,
  BLUESKY: BlueskyIcon,
  MASTODON: MastodonIcon,
  TUMBLR: TumblrIcon,
  WHATSAPP: WhatsappIcon,
  TELEGRAM: TelegramIcon,
  DISCORD: DiscordIcon,
  SIGNAL: SignalIcon,
  WECHAT: WechatIcon,
  MESSENGER: MessengerIcon,
  SKYPE: SkypeIcon,
  GITHUB: GithubIcon,
  GITLAB: GitlabIcon,
  SPOTIFY: SpotifyIcon,
  SOUNDCLOUD: SoundcloudIcon,
  LAST_FM: LastFmIcon,
  TWITCH: TwitchIcon,
  KICKSTARTER: Kickstarter01Icon,
  SHOPIFY: ShopifyIcon,
  PAYPAL: PaypalIcon,
  STRIPE: StripeIcon,
  WEBFLOW: WebflowIcon,
  WORDPRESS: WordpressIcon,
  ZOOM: ZoomIcon,
  WIKIPEDIA: WikipediaIcon,
  PEXELS: PexelsIcon,
  UNSPLASH: UnsplashIcon,
};

export function getCategoryIcon(category: string | null | undefined) {
  if (!category) return null;
  const icon = iconMap[category];
  if (!icon) return null;
  return <HugeiconsIcon icon={icon as never} size={16} />;
}

export const traitCategoryGroups = [
  {
    label: "Contact Info",
    options: [
      { value: "PHONE_NUMBER", label: "Phone Number" },
      { value: "EMAIL", label: "Email" },
    ],
  },
  {
    label: "Social Media",
    options: [
      { value: "FACEBOOK", label: "Facebook" },
      { value: "INSTAGRAM", label: "Instagram" },
      { value: "LINKEDIN", label: "LinkedIn" },
      { value: "YOUTUBE", label: "YouTube" },
      { value: "REDDIT", label: "Reddit" },
      { value: "PINTEREST", label: "Pinterest" },
      { value: "SNAPCHAT", label: "Snapchat" },
      { value: "THREADS", label: "Threads" },
      { value: "BLUESKY", label: "Bluesky" },
      { value: "MASTODON", label: "Mastodon" },
      { value: "TUMBLR", label: "Tumblr" },
    ],
  },
  {
    label: "Messaging",
    options: [
      { value: "WHATSAPP", label: "WhatsApp" },
      { value: "TELEGRAM", label: "Telegram" },
      { value: "DISCORD", label: "Discord" },
      { value: "SIGNAL", label: "Signal" },
      { value: "WECHAT", label: "WeChat" },
      { value: "MESSENGER", label: "Messenger" },
      { value: "SKYPE", label: "Skype" },
    ],
  },
  {
    label: "Dev/Tech",
    options: [
      { value: "GITHUB", label: "GitHub" },
      { value: "GITLAB", label: "GitLab" },
    ],
  },
  {
    label: "Music",
    options: [
      { value: "SPOTIFY", label: "Spotify" },
      { value: "SOUNDCLOUD", label: "SoundCloud" },
      { value: "LAST_FM", label: "Last.fm" },
    ],
  },
  {
    label: "Streaming",
    options: [
      { value: "TWITCH", label: "Twitch" },
      { value: "KICKSTARTER", label: "Kickstarter" },
    ],
  },
  {
    label: "Business",
    options: [
      { value: "SHOPIFY", label: "Shopify" },
      { value: "PAYPAL", label: "PayPal" },
      { value: "STRIPE", label: "Stripe" },
      { value: "WEBFLOW", label: "Webflow" },
      { value: "WORDPRESS", label: "WordPress" },
    ],
  },
  {
    label: "Other",
    options: [
      { value: "ZOOM", label: "Zoom" },
      { value: "WIKIPEDIA", label: "Wikipedia" },
      { value: "PEXELS", label: "Pexels" },
      { value: "UNSPLASH", label: "Unsplash" },
    ],
  },
  {
    label: "Links",
    options: [
      { value: "SOCIAL_MEDIA_LINK", label: "Social Media Link" },
      { value: "WEBSITE_LINK", label: "Website Link" },
    ],
  },
] as const;
