services:
  postgres:
    image: postgres:17
    hostname: postgres
    environment:
      - POSTGRES_USER=social
      - POSTGRES_PASSWORD=links
      - POSTGRES_DB=social_links
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
volumes:
  db: